name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: ./
        name: One Value Select
        id: one_value_select
        with:
          value0: hello
      - name: Test One Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.one_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal 'hello'. actual: ${ACTUAL_VALUE}" && exit 1)

      - uses: ./
        name: First Value Select
        id: first_value_select
        with:
          value0: hello
          value1: goodbye
          value2: howdy
          value3: partner
          value4: chicken
      - name: Test Second Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.first_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal hello." && exit 1)

      - uses: ./
        name: Second Value Select
        id: second_value_select
        with:
          value0: 
          value1: hello
          value2: howdy
          value3: partner
          value4: chicken
      - name: Test Second Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.second_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal hello." && exit 1)

      - uses: ./
        name: Third Value Select
        id: third_value_select
        with:
          value0: 
          value1: 
          value2: hello
          value3: partner
          value4: chicken
      - name: Test Third Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.third_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal hello." && exit 1)

      - uses: ./
        name: Fourth Value Select
        id: fourth_value_select
        with:
          value0: 
          value1: 
          value2: 
          value3: hello
          value4: chicken
      - name: Test Fourth Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.fourth_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal hello." && exit 1)

      - uses: ./
        name: Fifth Value Select
        id: fifth_value_select
        with:
          value0: 
          value1: 
          value2: 
          value3: 
          value4: hello
      - name: Test Fifth Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.fifth_value_select.outputs.selected_value }}
        run: |
          [[ "${ACTUAL_VALUE}" == hello ]] || \
            (echo >&2 "Expected to equal hello." && exit 1)

      - uses: ./
        name: No Selectable Values
        id: no_value_select
      - name: Test Fifth Value Select
        shell: bash
        env:
          ACTUAL_VALUE: ${{ steps.no_value_select.outputs.selected_value }}
        run: |
          [[ -z "${ACTUAL_VALUE}" ]] || \
            (echo >&2 "Expected to be empty." && exit 1)
