name: Move Major Version Tag on Release

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  move_major_version_tag:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      - uses: cgrindel/gha_configure_git_user@v1
      - name: Resolve release_tag
        id: resolve_release_tag
        uses: ./
        with: 
          value0: ${{ github.event.release.tag_name }}
          value1: ${{ github.event.inputs.release_tag }}
      # TODO: FIX ME
      # - uses: cgrindel/gha_move_major_version_tag@v1
      - uses: cgrindel/gha_move_major_version_tag@debug_other_repo_using_action
        with:
          release_tag: ${{ steps.resolve_release_tag.outputs.resolved_value }}
          # TODO: FIX ME
          checkout_ref: debug_other_repo_using_action
